[workspace]
authors = ["Karson Chrispens <karson.chrispens@ucsf.edu>"]
channels = ["conda-forge"]
name = "distogram_analysis"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
biopython = ">=1.85,<2"
python = ">=3.12.11,<3.13"
numpy = ">=2.3.2,<3"
pandas = ">=2.3.1,<3"
ruff = ">=0.12.8,<0.13"
scikit-learn = ">=1.7.1,<2"
matplotlib = ">=3.10.5,<4"
seaborn = ">=0.13.2,<0.14"

[pypi-dependencies]
rcsb-api = ">=1.3.0, <2"
